### ISSUE TITLE
Font improvements: Fallbacks, Umlaut ß etc.

### ISSUE THREAD

**Issue by mhilbrunner** [foundryvtt/dnd5e#2381]
Currently, there are various challenges around how fonts are used in the system:

1. One of the main fonts used is one of the `Modesto Condensed` variants.
    1. This is a commercial font, best I can tell, so while close to D&D 5E, it is hard to create and ship modifications for.
    1. This does not contain some widely used characters, like the German umlaut `ß`, which is unfortunately common. Worse, it uses `~` for these characters it does not contain, so instead of falling back to other fonts, all these characters get rendered as `~`.
1. `Palatino Linotype` is defined as the first and only fallback for `Modesto Condensed`. This font looks extremely different and best I can tell, breaks the layout of most of the 5E sheets currently. Having this defined seems to hurt more than it helps?
1. It is quite cumbersome to replace fonts currently, as they are defined in many places (ref. https://github.com/foundryvtt/dnd5e/issues/1413). Currently, I need to do this, which seems brittle and may require changes for each update:
```css
.modesto,
.dnd5e .form-header,
.dnd5e.sheet .sheet-header .header-details,
.dnd5e.sheet .sheet-header .header-details .summary select,
.dnd5e.sheet .sheet-navigation,
.dnd5e .items-list .items-header h3,
.dnd5e.sheet.actor h4.box-title,
.dnd5e.sheet.actor ul.attributes li.attribute .attribute-value,
.dnd5e.sheet.actor .ability-scores,
.dnd5e.chat-card .card-header h3,
.dnd5e.sheet.actor.character .characteristics label,
.dnd5e.sheet.group .members .directory-header > * {
   font-family: ...
}
```

Suggestions:
1. Define fonts in central places and make them easy to modify
2. Use fonts that support common characters in western languages, like umlaut `ß`
3. Use open fonts licensed freely so that it is legal and easy to modify and use them in modules and distribute copies
4. Use fallback fonts that are tested and don't break the layout and, optimally, look somewhat similar to what they replace

Thanks for working on Foundry and 5E!
