### ISSUE TITLE
Header buttons unaligned, item containers border overflowing

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/dnd5e#2952]
Header buttons - Current vs Fixed

![image](https://github.com/foundryvtt/dnd5e/assets/1346839/5859c2b1-130f-43cb-b661-64dd9ec0eea5)

Fix

```css
    .header-button {
        background: rgba(0, 0, 0, 0.25);
        height: 1.3em;
        aspect-ratio: 1;
        text-align: center;
        place-self: center;
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 50%;
        i{
            margin: 0;
        }
    }
```

Item containers overflow - current vs fixed

![image](https://github.com/foundryvtt/dnd5e/assets/1346839/8396d0ba-74b2-43e1-8fd4-9d172a5a1c86)

![image](https://github.com/foundryvtt/dnd5e/assets/1346839/89ffcfe0-9d61-4138-a117-317ee2b1898e)

To remove the blue line overflow, add overflow hidden here

![image](https://github.com/foundryvtt/dnd5e/assets/1346839/37160e2b-9981-4d69-8489-7819671360f0)
