### ISSUE TITLE
Group Actor type field does not play nice with different core font size

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#3584]
Pictured: Font Size 6. 
![image](https://github.com/foundryvtt/dnd5e/assets/148253744/fa2014a0-0a2f-4b35-9ba4-beb65622baaa)
Font Size 7
![image](https://github.com/foundryvtt/dnd5e/assets/148253744/bb1536a7-3471-4fb4-a781-aabbc65e7270)

(Chrome, no modules, v11.315, dnd5e 3.1.2

Since the character sheets now better support font sizes at least one above default (at least the PC sheet, the NPC sheet still has some trouble but with the new one on the way its probably not worth a look right now), it would be nice if the new group actor did as well.

```css
.dnd5e.sheet.actor .sheet-header .summary select {
  height: 24px;
  line-height: 24px;
}
``` 
From my brief testing, adding the same height and line-height as the .summary span might add support for at least font size 7.
