### ISSUE TITLE
Expanded damage roll damage types word wrap ungracefully on font size 6+

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#4266]
![image](https://github.com/user-attachments/assets/4bc2ce3c-c100-482e-bc2e-45635af5c7f0)

when reproducing, bear in mind this does not occur in a chat log with no scrollbar. once there are enough messages for a scroll bar to appear, it occurs

could perhaps be fixed with something like 
```css
  /*...*/ .dice .total .label { white-space: nowrap; }
```
