### ISSUE TITLE
Add horizontal scroll to journal tables

### ISSUE THREAD

**Issue by Greatshock** [foundryvtt/dnd5e#4894]
## Problem
With default journal width, some content in tables in PHB 2024 is not visible. See example below: 
<img width="662" alt="Screenshot 2024-12-16 at 10 29 52 PM" src="https://github.com/user-attachments/assets/f5b2e6bc-2e08-462e-a1fd-78f31632435a" />

## Proposed solution
```css
table.features-table {
    /* width: fit-content; <--- this need to be removed */
    display: block;
    overflow-x: auto;
}
```
