### ISSUE TITLE
[feature] character sheet adding right hand side padding or margin

### ISSUE THREAD

**Issue by johnweland** [foundryvtt/dnd5e#4932]
Not sure if it's a feature request or perhaps a bug, but in the character sheet there seems to be no padding or margin on the right hand side. things are nestled right to the edge. Even resizing the sheet the "gears" icons to click to make changes are still pushed right the edge.

Ideally for accessibility those icons would have a 40px by 40px clickable area. I think adding a padding or margin on the right side of the sheet to match they left side of the sheet would be a great improvement

![Screenshot 2024-12-27 at 8 32 24 AM](https://github.com/user-attachments/assets/fb718b37-2795-417f-b63f-12122d23839a)
![Screenshot 2024-12-27 at 8 31 47 AM](https://github.com/user-attachments/assets/fb62d7da-1730-422a-bf0c-33410db2ed40)
![Screenshot 2024-12-27 at 8 31 55 AM](https://github.com/user-attachments/assets/331b1a0a-2902-4544-a75d-399ac1bb3b1e)

**Comment by johnweland** [comment]
```css
.dnd5e2.sheet.actor.character .sheet-body .main-content {
    display: grid
;
    grid-template-columns: var(--dnd5e-sheet-sidebar-width) 1fr;
    gap: 12px;
    position: absolute;
    inset: 0;
    padding: 8px;
    /* padding-inline-end: 0; */
    overflow: hidden auto;
    scrollbar-width: thin;
    scrollbar-gutter: stable;
    scrollbar-color: var(--dnd5e-color-scrollbar) transparent;
    transition: all 450ms ease;
}
```


it seems to be fixed by disabling the CSS property `padding-inline-end: 0;` from the section above
